on: push
jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-2019
    container:
      image: mcr.microsoft.com/windows/servercore:ltsc2019
    steps:
      - run: ...
  first-job:
    runs-on: windows-latest
    container: node:17.6.0
    steps:
      - run: node --version
      - run: npm --version
